(defproject com.hjsoft/clojure-scratch "1.0.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.11.1"]
                 [org.clojure/data.xml "0.0.8"]
                 [org.clojure/data.csv "1.0.1"]
                 [org.clojure/core.logic "1.0.1"]
                 [org.clojure/math.combinatorics "0.1.6"]
                 [org.clojure/data.zip "1.0.0"]
                 [cljc.java-time "0.1.18"]
                 [clojure.java-time "0.3.3"]
                 [org.clojars.gnzh/feedparser-clj "0.6.0"]
                 [hiccup "1.0.5"]
                 [seancorfield/next.jdbc "1.2.659"]
                 [com.h2database/h2 "2.1.214"]
                 [hugsql-next-jdbc "0.1.3"]
                 [clj-commons/clj-yaml "0.7.108"]
                 [clj-http "3.12.3"]
                 [hawk "0.2.11"]])
