(defproject com.hjsoft/clojure-scratch "1.0.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.10.2"]
                 [org.clojure/data.xml "0.0.8"]
                 [org.clojure/data.csv "1.0.0"]
                 [org.clojure/core.logic "1.0.0"]
                 [org.clojure/math.combinatorics "0.1.6"]
                 [org.clojure/data.zip "1.0.0"]
                 [cljc.java-time "0.1.15"]
                 [clojure.java-time "0.3.2"]
                 [hiccup "1.0.5"]
                 [seancorfield/next.jdbc "1.1.613"]
                 [com.h2database/h2 "1.4.200"]
                 [hugsql-next-jdbc "0.1.3"]
                 [clj-commons/clj-yaml "0.7.106"]
                 [clj-http "3.12.1"]
                 [hawk "0.2.11"]])
